lib/index.js, test/nickname-test.js
I thought it'd be helpful to be able to override the automatically generated nickname with one provided in the route.
For example:
```
server.route({
method: 'GET',
path: '/user/{username}/friends/',
config: {
plugins: {
'hapi-swagger': {
nickname: 'getFriendsByUsername'
}
},
handler: function(request, reply){
reply('ok');
},
description: 'Get friends for username.',
notes: ['Returns friends for the provided username.'],
tags: ['api'],
validate: {
params: {
username: Joi.string()
.min(3)
.max(10)
.required()
.description('the username')
}
}
}
});
```
=> Added support for overriding auto-generated nicknames in route config

public/swaggerui/swagger.html
I just removed the inclusion of the nonexistent readme.css which caused a 404.
I guess it is unused.
=> Remove the inclusion of the nonexistent readme.css which caused a 404.

public/swaggerui/swagger-ui.js
Hi there
The method build() on the SwaggerUi object was called twice and cause two ajax requests. I removed the line because the object call this method during its init (line 44 of swagger.js).
=> Remove an useless call to .build()

lib/index.js
And use the cleaned up `value` parameter instead of `settings.info`.
I'm using the popular [node-config](https://github.com/lorenwest/node-config) module to manage all sorts of hapi configuration option (including parameters for hapi-swagger). Unfortunately it seems to inject additional functions to help merging parts of the configuration options, thus the validation of `settings.info
` will fail. This can easily be fixed by asking Joi to drop all unknown additional keys.
=> Strip unknown fields from settings.info during validation

lib/index.js
If you're using hapi's "good" module to handle centralized logging, information
might get overlooked when pushing it directly to the console. To avoid this,
use the logging method `server.log` provided by the hapi framework itself.
=> Use hapi's server.log() instead of console.log()

lib/index.js
Found out when I browse the documentation on iOS (setup: endpoint: /docs/json; docs auth: none, resources/rest of routes auth: simple) it asks for '/docs/swaggerui/images/throbber.gif' for which auth option is not configurable. Thus if you have global rule to use auth on every route and then disabling auth for documentation (just for viewing) it asks for credentials. No prob on other browsers (Chrome, IE, FF, Edge...)
=> Added auth option for fixed path to throbber.gif

public/swaggerui/lib/swagger.js
I got an error, if I use the PasswordAuthorization method. Because an illegal invocation. I fixed it, with the binding.
=> Fix uncaught type error

lib/index.js
A quick fix to stop the 'model' variable from being added to the global namespace.
=> fix 'model' variable added to global namespace

README.md, lib/index.js, test/base-path-test.js
Thanks again for the awesome repo! Our hapi API lives behind a reverse proxy, so it is important that all of the URLs generated by the swagger docs use the protocol and port in the `x-forwarded` headers. 
Accomplishing this was fairly simple, but in the process of writing tests, I found that it was difficult to reason about how `requestSettings.baseUrl` was defined. For instance, if `options.protocol` was set in the plugin options, and `options.baseUrl` was also set, then `options.baseUrl` would override `options.protocol`. Further, there were cases where `options.baseUrl` would be appended to the hostname derived from the headers.
Based on this behavior, I decided to rewrite how `baseUrl`is derived. I used the `url` native Node utility to parse the `options.baseUrl`, and override each …
=> Add proxy host and proto to basePath

lib/index.js
Fixes glennjones/hapi-swagger#145
In Hapi >= 9, the `request` has a `connection` property with method `table()` that returns the `table` object for that connection. The previous version of the code would select the first labeled connection instead of the connection passed to the plugin.
=> Fixes glennjones/hapi-swagger#145

lib/index.js, test/prefix-test.js
hapi doesn't allow specifying payload validation for proxy handler as payloads are not parsed for these. 
@hueniverse suggest this [should be plugin specific config](https://github.com/hapijs/hapi/issues/2260#issuecomment-65923893) in this case (like response schemas). 
With my change we try to read payload params from plugin specific config when it's not found under validate config.
=> Allow specifying payload params for proxy handler

lib/index.js
Client-provided variable should be escaped before in use for regex. Leads otherwise to syntax errors if it results in an invalid regex, e.g. `/docs?path=foo(`
Credit for escape regex to bobince on http://stackoverflow.com/a/3561711/134162
=> fix 500 response if regex control chars in path param

README.md
The mis-matched case prevents the example from working out of the box.
=> Fix casing for `Pack`  variable.

README.md, lib/index.js, package.json
I love the plugin. However I don't need a documentation page on my API and I have no need for inert or vision in my API. So I have simply move the plugin check and view config inside of the check for "documentationEnabled" this way I can point API Gateway at the generated swagger.json for documentation and have my CI download the swagger.json for use in swagger-codegen
If there are any changes you want me to make or any concerns about this PR please just let me know
=> Remove the need for inert and vision when doc endpoint is disabled 2

lib/properties.js, test/properties.js
See #212 for details.  Basically– `null` isn't allowed in an `enum` field per the OpenAPI spec, so we're not going to put it there :)
=> Ignore allow(null) on properties, per OpenAPI spec.

lib/properties.js, test/properties.js
```js
let user = Joi.schema({ {
name:Joi.string()
}).label('User')
let schema = Joi.schema({
createdBy:User,
editedBy:User
})
```
would have become in the /docs page:
```js
definition {
User:User
}
User {
name:"string"
}
```
after fix will stay
```js
definition {
createdBy:User,
editedBy:User
}
User {
name:"string"
}
```
parse label should reflect to definition name only, and not change the properties key
=> #fix keys were replaced by labels

lib/builder.js, test/proxy-test.js
Azure Web Sites does not use `x-forwarded-proto`, while `connection.info.protocol === 'socket'` on their environment due to how iisnode is working.
`getSchema` returning `socket` does not pass the Joi validation and fails hapi-swagger with 500 error on GET /swagger.json.
This fix uses `x-arr-ssl` header from Azure environment as indication that user had send request usign HTTPS.
Request send over HTTP would still result in `socket` schema. And I have no idea on how to solve this without breaking `ws` and `wss` schema detection.
=> Use x-arr-ssl header to find requested protocol

lib/builder.js, test/helper.js, test/proxy-test.js
In continuation to pull request #231, here is a change which assumes that if protocol is `socket` then request came over `http`.
This is not ideal, but given that `socket` is not considered valid and errors `GET /swagger.json` with 500 error - I propose to give it a try.
I am not planning to use WebSockets on Azure environment for now, so I could not contribute for `ws` and `wss` detection there.
=> Assume that if protocol is socket then request was made using HTTP

lib/index.js, test/plugin-test.js
Loading the plugin with a route prefix (that might be inherited from a parent plugin) broke all the resource paths within the documentation UI:
- The HTML was rendered without taking the prefix into account
- All route declarations are automatically prefixed
=> The browser can’t load any of the UI resources
=> Fix: Loading the plugin with a route prefix broke documentation UI

lib/builder.js, lib/index.js, test/document-other-connection-test.js
Firstly, thanks for maintaining this repo! I've used it in several projects, and it is amazing.
At present, I would like this PR to start a conversation about a feature that is very important to me and my team: Serving documentation on one connection for an API that is on a separate connection. This was brought up at least once before in #187 
We are in a similar position to @bboysathish: Our API is served on one port, which is exposed to the public via a load balancer, and our docs are exposed on different ports that is not exposed to the public web. 
I've made some quick changes that will for a plugin option `connectionLabels`. This options will specify which connection to generate the swagger.json from, regardless of which connection is handling the request currently. Would you mind …
=> Separate ports

lib/definitions.js
quickly made something
you will see 3 files here  https://gist.github.com/catalint/68943916badc2cbd62c6030434159005 a before , after , and app to test away
the before has some extra model definitions that get removed after using the cache
there still is an extra model definition there, but that's another issue to solve , not related to this
fixes #251 and #250
=> use weakMap to keep definitions from duplicating

lib/properties.js, test/file-test.js
hapi-swagger currently demands that file upload fields are specified as `joi.any()` but if you want the file to be submitted to the route handler as a buffer, `joi.binary()` is required (afaik). An example:
```JavaScript:
…
validate: {
payload: {
someFormField: joi.string().required(),
anotherFormField: joi.string().required(),
theFile: joi.binary().required().meta({swaggerType: 'file'})
}
}
…
```
This PR relaxes hapi-swagger’s property parsing to allow the `.meta({swaggerType: 'file'})` annotation on _any field_  not just `any()` fields 😉.
=> Fix: other types than `any` (eg. `binary`) can be file uploads too

.eslintrc.json, .travis.yml, bin/document-other-connection.js, bin/swagger-client.js, bin/test-server-connections.js, bin/test-server-custom.js, bin/test-server-promise.js, bin/test-server-versions.js, bin/test-server.js, lib/index.js, package.json, test/connections-test.js, test/helper.js, test/plugin-test.js
I was digging into a different issue, but I found my editor erupting with red underlines and angry status bar messages about lint errors. It turns out that the linting was never being run during `npm test` (the `-L` option passed to `lab`), despite all the config hanging around. It really should be.
I took great pains to minimize the diffs, especially trivial whitespace. Some of the callback indentation errors, for example, could have been fixed with actual reduction of indent, but that's a noisy diff avoided by a simple newline before the arrow callback.
The Travis tweaks allow it to run `npm test` (gaining the new lint validation as well as actually logging stuff) while still publishing the coverage after a successful build.
1a112fe is not exactly related to linting, but was causing the …
=> Run lint during `npm test`, with config tweaks & fixes

lib/definitions.js
Previously, required:false was creeping into the JSON output where it
shouldn't. This breaks in strange ways on some parsers.
I apologize, but I'm not quite sure how to add a test for this bug.
=> Always clearing the `required` field inside of objects in a definition

package.json
Hapi v14.0.0 has been released 3 days ago, with a little change. (See: https://github.com/hapijs/hapi/issues/3272)
Since we already using Joi v9, It would work without any problems.
=> Add hapi v14 to peer dependencies

public/swaggerui/index.html
SwaggerUI attaches event handler to apiKey input that wants to refresh UI (pull swagger.json). It uses baseUrl input to do that refresh, so we need to have that input in our DOM.
=> Properly refresh UI when user hits enter after entering apiKey.

.editorconfig, .gitattributes, lib/index.js
* Added editorconfig to force IDE to follow team standard whitespace
* Added gitattributes to force Git to use LF not Windows line endings
* Update path so Windows (and hopefully POSIX) tests all pass
=> Windows: All tests pass with team whitespace rules (#381)

lib/paths.js
I've noticed that `operationId` includes whole path including `basePath` that is specified in settings. 
For some cases it might be very inconvenient.
I'm using `swagger-client` and my REST api is prefixed with `/rest/api/v2/`
So the resulting methods look like `client.permissions.getRestApiV2Permissions`
instead I'd like to see `client.permissions.getPermissions`. 
Fortunately enough it was an easy fix.
=> OperationId. Remove basePath prefix from operationId

lib/properties.js
Small bug fix: 
`property` can be undefined on line 529 of property.js, because `parseProperty()` on line 514 might return `undefined` (for instance if there is a Joi.forbidden()). Line 529 will then throw a TypeError (trying to set x-alternatives on undefined)
=> Bug fix: Don't set x-alternatives on property if property is undefined

lib/info.js, optionsreference.md, test/Integration/info-test.js
Any options info property or object with a key starting with *x-* is included as such in the *info* section of the object returned by the JSON endpoint. This allows custom properties to be defined as options and copied as such.
No change to UI page as there isn't necessarily a standard way of displaying such custom properties.
With unit test and proposed updated README
Output of  `npm test`:
```
$ npm test
> hapi-swagger@7.6.0 test D:\GitHub\public\hapi-swagger
> lab -L -t 100
..................................................
..................................................
..................................................
..................................
184 tests complete
Test duration: 3388 ms
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
``` …
=> Allow custom options info properties

lib/index.js, public/swaggerui/index.html
There was an issue with loading swagger UI with `auth` specified: in this case the base URL `/documentation` would load, but not any of the dependent resources.
This PR attempts to fix the forementioned issue by:
* Removing `auth` settings from the public resources (css, scripts, libs)
* Adding `access_token` query param to the URL of the `swagger.json` during the initialization of the `SwaggerUI` object
=> Fix `auth` setting to fully load the swagger UI

package-lock.json, package.json
This makes quite a difference in the bundle size when using serverless.
I've made sure that lab is not required anywhere in lib and created a [new npm package ](https://www.npmjs.com/package/@tepez/hapi-swagger) to test this.
=> Move "lab" from dependencies to devDependencies

lib/builder.js, lib/defaults.js, lib/definitions.js, lib/index.js, optionsreference.md, test/Integration/definitions-test.js, usageguide.md
Currently the next model name is always "Model #". However if you have a dynamic model that uses the same label, but with different fields or description, then the numbering can balloon up very quickly.
I've added an option called "definitionPrefix", which when set to "useLabel", will use the label as the numbering base. E.g. If I have a model called "baseErrors", then all my flavours of baseErrors will be "baseErrors 1", "baseErrors 2" etc, which is better to read.
=> Added option to use "label" as the next model name prefix

.gitignore, lib/properties.js, test/unit/property-test.js
Joi.allow() creates a valid list that results on dropdown in Swagger
docs UI. This is not expected in many cases and here we add
`disableDropdown` meta property for those.
One example that is used in tests is non-negative integers that could
not be edited in swagger UI forms:
Joi.number().integer().positive().allow(0)
Only by adding `.meta({disableDropdown: true})` one could make this
editable as a form field.
Let me know if there is a better way to achieve this or the PR needs changes.
=> Disable dropdown for a property in UI via meta

usageguide.md
The anchor wasn't working (at least for me Chrome on Mac) due to the capitalisation of the anchor.
=> Corrected anchor for "Grouping endpoints by path or tags"

README.md
This is just a quick update to change the README. It fixes a variable name in the quick start section and also fixes the async code as you cannot use `await` outside of an async function.
No changes to functional code.
```
183 tests complete
Test duration: 1894 ms
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
```
=> Update readme to fix async code and variable name

README.md
Since hapi v17 the "config" property is named "options" (see "Breaking Changes" in https://github.com/hapijs/hapi/issues/3658).
=> Rename config property

package.json, test/Integration/authentication-test.js, test/helper.js
- add back JWT tests
- pin swagger-parser to `v4.0.2`. [PR #83](https://github.com/BigstickCarpet/swagger-parser/pull/83) and [PR #84](https://github.com/BigstickCarpet/swagger-parser/pull/84), were added to improve the the [`validate()` method](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#validateapi-options-callback) and should  now detect when a JSON Schema in an API definition has `required` properties that don't exist. Unfortunately, the fixes don't take into account `$ref` which caused two unit test to break:
```
129) responses array with required #249:
Expected false to be true
at lab.test (/.hapi-swagger-fixes/test/Integration/responses-tests.js:697:35
130) responses replace example with x-example for response:
Expected false to be true
at …
```
=> JWT Tests and pin swagger-parser to 4.0.2

lib/properties.js, test/unit/property-test.js
Currently, tools like Swagger UI that support pattern="<regex>" validation fail for any endpoint from the hapi-swagger-generated document that includes a pattern. Tools are using new RegExp(strExp) for parsing and don't expect to see the slashes etc (see https://github.com/swagger-api/swagger-ui/blob/master/src/core/utils.js#L465)
From the examples, it looks like OpenAPI defines an element "pattern" as a RegularExpressionBody, not the full form with the RegularExpressionFlags and slashes (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md, https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5). Tools like Swagger UI expect the pattern to be in the source/RegularExpressionBody form.
There seems to be a related issue #418 that would be fixed by this PR.
Here's …
=> RegExp pattern in generated swagger.json should be compatible with the Swagger UI and other tools

lib/properties.js, test/Integration/builder-test.js, test/Integration/child-model.js, test/Integration/responses-tests.js, test/unit/property-test.js
When using $refs [all sibling elements are ignored][1] and causes [https://editor.swagger.io][2] to display an error when parsing `swagger.json` files produced by `hapi-swagger`.
Fixes #517
[1]: https://swagger.io/docs/specification/using-ref/#sibling
[2]: https://editor.swagger.io
=> Removes `type` field from arrays when `$ref` is present

lib/builder.js, test/Integration/builder-test.js
This fixes issues when the hapi server is running on a different host/port to the external interface, e.g. within Docker.
Fix #497
=> fix: Use the incoming request to determine the host and port

usageguide.md
in hapi 17+,
the route use like:
```
server.route({
method: 'GET',
path: '/',
handler: (request, h) => {
return 'Hello';
}
});
```
see: https://hapijs.com/tutorials
=> fix usageguide.md for hapi 17+

lib/properties.js
Fixed an issue #572: "field examples not appear correctly in swagger.json and swagger-ui"
=> Fix issue when field examples not appear correctly in swagger.json and swagger-ui

lib/properties.js, test/unit/property-test.js, usageguide.md
Currently using date().min() and date().max() will result in an invalid swagger.json,
for example:
`date().min('1-1-1974')` will result in
```json
{
"format": "date",
"maxLength": "now",
"type": "string"
}
```
Which is both invalid since maxLength must be an integer and obviously not what is meant by the Joi schema.
Couldn't find a reference that OpenAPI indeed doesn't support date range rules, but found no refrence that it does support it either.
Fixes #417
=> Ignore date.min() and date.max() to avoid creating invalid swagger

package-lock.json, package.json
I noticed that this was out of date (as well as joi, which I saw that you're working on https://github.com/glennjones/hapi-swagger/issues/577).
Also, is there any plan to upgrade `swagger-parser` beyond 4.0.2, after they made the validate function stricter? That upgrade breaks 3 tests because they are missing parameters, but fixing that would unlock swagger v3
=> Upgrade json-schema-ref-parser to v6

usageguide.md
Not sure what version Hapi.js introduced the `response.status` but after trying it out with hapi-swagger today it turns out that Swagger-UI does recognize this option, however the Docs didn't demonstrate this so I decided to write about it.
If there is some limitation with this option, please let me know.
I made sure to document the differences between the `response.status` and the `plugin.hapi-swagger.responses` options for full clarification.
=> Docs: explain how to use Hapi.js `response.status` for multiple status codes

usageguide.md
Had a wrong syntax for the `response.status` option in my previous PR (re: [PR #580](https://github.com/glennjones/hapi-swagger/pull/580)), and just noticed it so here's the fix for that. 
Also fixed whitespace formatting to align with existing style.
Thank you!
=> Docs: fix option syntax, fix formatting

examples/custom.js, index.d.ts, lib/builder.js, lib/defaults.js, lib/index.js, optionsreference.md, test/Integration/documentation-route-plugins-test.js
i want to add the plugins option to the documentation route because my project have using `blankie` when i access to the document page it cant download the script because of following this rules
```js
{
fontSrc: ['self', 'fonts.gstatic.com', 'data:'],
scriptSrc: ['self', 'unsafe-inline'],
styleSrc: ['self', 'fonts.googleapis.com', 'unsafe-inline'],
imgSrc: ['self', 'data:'],
generateNonces: false
}
```
so i have to add those config to globally at `blankie` plugin and i don't want to do it becuase my other route is gonna be restricts .
if this can fix my issue or any other who use `blankie` or any other plugin that want to specify for that only route .
=> add option plugins for documentation route

lib/definitions.js
Spaces plus encodeUriComponent yields a %20 which is not a valid identifier
#599
=> Remove spaces from generated model names

lib/properties.js, test/unit/property-test.js
This PR adds `additionalProperties` keyword on the generated schema, when Joi object is created with `unkown(false)` option
=> feat: add support for additional properties in object schemas

lib/index.js
=> fix: add documentationRouteTags to swagger ui assets routes

README.md, optionsreference.md, usageguide.md
With the change to Joi@16 (and the requirement for Joi.object
to be present in the route.validate* options) there were
several docs samples where this was missing. This commit
corrects these instances.
Missing the top level Joi.object is associated with:
UnhandledPromiseRejectionWarning: Error: Invalid schema content
=> docs - Top level Joi.object in samples

lib/responses.js, test/Integration/responses-tests.js
Ref.: https://github.com/glennjones/hapi-swagger/issues/392
=> Fix: Validating and documenting a 204 No Content endpoint

.npmrc, index.d.ts, lib/builder.js, lib/defaults.js, lib/index.js, optionsreference.md, test/Integration/plugin-test.js, test/helper.js
Hello, everyone.
This PR responds to a problem I've found recently when using hapi-swagger in some production environments:
At some clients I've worked at, it's not unusual to have a main domain and then have a bunch of APIs behind it in different paths /api1, /api2...
The problem that hapi-swagger has with this kind of setup is that the moment you configure the swaggerUIPath as /api1, the frontend assets point to the correct place, but the routes are created as /api1/ASSET, which, in reality makes the asset routes to be exposed in /api1/api1/ASSET.
This PR adds a new option, routesBasePath, which allows for splitting the routes and swaggerUI paths for avoiding this problem.
To avoid breaking existing behaviour due to adding something that seems is not an urgent need for everyone (I …
=> Add routesBasePath option so that routes can listen in different paths than swaggerUIPath

lib/properties.js, test/unit/property-test.js
Fixes https://github.com/glennjones/hapi-swagger/issues/652
I had to `--no-verify` when committing because the code coverage threshold did not pass when the testsuite was limited to just the single file that was updated (lib/properties.js), which is how it runs from within `lint-staged`, however the overall coverage percentage (when run directly as `npm test`) is still showing 98.05%.
=> Fix pattern generation to avoid truncating regex at internal "/"

index.d.ts
Currently the swagger options' type is expecting `tags` to be an object but in reality it is an array of objects.
=> fix type: tags is an array

lib/properties.js, test/unit/property-test.js
- added a check to avoid 'undefined of' when using regex as property pattern
- added unit test to cover regex as object property pattern
=> handle regex as pattern schema

package-lock.json, package.json
Update the boom library to v9. According to it's [changelog](https://github.com/hapijs/boom/milestone/60?closed=1) the only breaking change is that is requires Node >= 12. Since this library already requires that version, it shouldn't be a problem. I also updated the `engines` field to reflect the actual Node.js support.
=> Update @hapi/boom to v9

examples/jwt.js
Without the security property the authorization headers are never sent. I hope this helps other developers save time.
See: https://github.com/glennjones/hapi-swagger/issues/602#issuecomment-522129367
=> Updates JWT example to include Authorization headers

lib/builder.js, lib/index.js, optionsreference.md, test/Integration/plugin-test.js
should close: https://github.com/glennjones/hapi-swagger/issues/675
**Note:**
when running tests I keps receiving: `The following leaks were detected:CSS` regardless of the -I setting in package.json. Hopefully it's just a misconfiguration
=> Override server-level validation in plugin registration (via options)

package.json
Due to the separation of Joi from Hapi, I replaced the old dependency with the new one
=> Replace @hapi/joi with joi, as a peer dependency

lib/properties.js, test/unit/property-test.js, usageguide.md
Some properties that are used for internal purposes (and still need to be validated) are potentially unwanted in public-facing documentation. This PR adds support for such cases. Adding
`.meta({ swaggerHidden: true })`
will exclude property from the resulting spec.
=> Support for hiding Joi properties from being included in Swagger

lib/responses.js, test/Integration/responses-tests.js
Fix for https://github.com/glennjones/hapi-swagger/issues/695
=> fix: Use default 200 response when responses empty & given default schema

lib/properties.js, test/unit/property-test.js
Adding support for:
Joi.date().iso() -> { type: 'string', format: 'date-time' }
Joi.date().timestamp() -> { type: 'integer' }
Joi.date()-> { type: 'string', format: 'date' } // original behavior
I'd appreciate it if someone who knows the differences between Joi versions took a look at the way the Joi.date() format is detected. The old code didn't seem correct for the version i'm using. I left in a bit of backward compatibility.
sorry about the code format - `eslint --fix` did it's work :(
=> Fix for issue #323 - .date() vs .date().isoDate()

lib/properties.js, test/unit/property-test.js
Joi@17 started adding an override special value on allow/disallow lists (see [here](https://github.com/sideway/joi/blob/83092836583a7f4ce16cbf116b8776737e80d16f/test/base.js#L3490-L3490)), there appears to be no reliable way to detect that value, so I went as far as I could to make sure that's the one and strip it, but there's no guarantee.
Also, the tests don't pass locally based on coverage, but that's not really new.
=> Drop override values when present

lib/index.js, templates/index.html
There are 2 methods to use this ability.
1. Use inline script as plain string, eg:
```
{
...,
uiCompleteScript: 'alert("I got you !")'
}
```
2. Well, I know the world is not enough to write ideas in people mind as script into a "string", then alternatively use External file as URL, you may define from Hapi static route or other source, eg:
```
{
...,
uiCompleteScript: { src: '/assets/js/doc-patch.js' }
}
```
```
// example at external JS file (URL):  /assets/js/doc-patch.js
'use strict';
window.alert('I got you again .. ');
```
=> Implementing uiCompleteScript using both inline script or external URL

package.json
According to https://www.npmjs.com/advisories/1670
A new issues has been found from current versions of handlebars (current: 4.5.3)
ISSUES :  https://github.com/glennjones/hapi-swagger/issues/712
=>  Upgrade handlebars package to 4.7.7

index.d.ts
This PR adds the following type definitions:
- [Security Definition](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityDefinitionsObject)
- [Security Scheme](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securitySchemeObject)
- [Scope](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#scopesObject)
This is my first PR into the library, so please let me know if there should be any additional changes to wording. I took most of the descriptions directly from the links above and added the `x-*` support where OpenAPI supports it. The matrix of required values for each `type` of security scheme was difficult to follow, so I inlined the required fields for each `type` where it made sense.
=> Adds types for securityDefinitions, securitySchemes, and scopes

index.d.ts, optionsreference.md
This PR adds the following type definitions:
- [Security Requirement Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#security-requirement-object)
This PR also exposes the proper typing for the `security` property for the [root Swagger document](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#schema). This is already enforced through Joi [here](https://github.com/glennjones/hapi-swagger/blob/master/lib/builder.js#L46) which is validating the schema for this root object.
Root-level description is taken from https://swagger.io/specification/v2/
Inner-property description is taken from https://swagger.io/specification/v2/#security-requirement-object
=> Add security requirements type to root document

lib/index.js, test/Integration/plugin-test.js
When the plugin is registered multiple times, each `swagger.json` for each option is generated properly, but not for the documentation page rendered.
The plugin pass settings data to the renderer via registering the `onPostHandler` ext function to the server. This behaviour caused only the last registered one to intercept others' requests, applying their settings on whole documentation pages.
=> fix: docs are rendered only with the options in last registered plugin

lib/properties.js, test/unit/property-test.js, usageguide.md
Similarly to PR #742, this pull request allows to set the format field in all number properties as well, not limited to integer properties. 
As stated [here](https://swagger.io/docs/specification/data-models/data-types/), number properties can optionally have the format field with values `float` or `double`.
=> feat: add support for format field in number properties

examples/group-ordered.js, examples/routes-filtering.js, lib/filter.js, test/unit/filter-test.js
I've discovered that in cases when `jsonPath` or `swaggerUIPath` options are set (differ from default values), some of the endpoints registered by `hapi-swagger` can be exposed into the OpenApi doc, which is not desirable 
By endpoints registered by `hapi-swagger` I mean `swagger.json` and all the `swagger-ui` ones.
=> fix: Don't add routes created by hapi-swagger into documentation

lib/definitions.js, lib/group.js, lib/paths.js, lib/utilities.js
Remove redundant implementation of `String.prototype.startsWith`.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith), this native feature was added to Node.js `v4.0`
=> fix: replace "Utilities.startsWith" with native "String.prototype.startsWith"

lib/utilities.js, test/unit/utilities-test.js
I made refactoring for the function `Utilities.sortFirstItem` and added correct jsDoc definition. Also, I have fixed TODO(an issue when the function possibly may modify the arguments which is bad practice). I have added the missed test for this function and made sure that the function makes a deep copy of the input array and does not change the arguments.
=> Refactoring func sort first item

lib/utilities.js, test/unit/utilities-test.js
In this PR I have improved a few things:
- did not use deprecated [String.prototype.substr](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) method;
- simplified a lot of functions, making it more readable;
- used `String.prototype.includes` instead of `String.prototype.indexOf` when possible to speed up the function and make it more readable and do not perform two actions(find the index and check if the index is bigger than -1, like element present into array or string);
- was added more tests and test cases;
- was added one `TODO` to do not miss the important point and add tests later;
=> fix: small refactoring Utilities

examples/http2.js, lib/builder.js, test/Integration/http2-test.js, test/Integration/proxy-test.js
Fixes #748 by using `request.info.referrer` if available as the default host for swagger.
=> Fix #748 hostname issues with http2

.github/CONTRIBUTING.md, README.md, examples/custom.js, examples/http2.js, examples/options.js, examples/ssl.js, package.json, test/Integration/alternatives-test.js, test/Integration/grouping-test.js, test/unit/property-test.js
Small change to update all the urls so they point to the new https://github.com/hapi-swagger/hapi-swagger/ repo rather the the old one under may name
=> chore: update repo urls to hapi-swagger

lib/index.js, lib/utilities.js, test/unit/utilities-test.js
This PR removes the usage of some deprecated modules into Node.js and add missed test. For example `querystring` and part of `url` modules.
There are a few links:
- [querystring](https://nodejs.org/api/querystring.html#query-string)
- [format](https://nodejs.org/api/url.html#urlformaturlobject)
- [parse](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost)
=> fix: Remove deprecated and legacy components

lib/definitions.js, package.json, test/Integration/responses-tests.js, yarn.lock
Fix for issue #736 and #762 update swagger-parser module.
- update swagger-parser to latest version
- make "required" property only applicable for objects not arrays in swagger output
- update tests to correct the error of "required" keyword on an array
=> fix: issue #736 no required for arrays in swagger

lib/utilities.js
This PR aims to allow null as a valid value for examples, default values and security.
This can be useful for APIs that accept patches with null values for instance.
Minimal test app : https://github.com/AppeninTerenceBARBE/test-hapi-swagger
Test with the branch `feat/use-null-fork`
**Example before:**
**Example after:**
=> feat: enable null values in examples

lib/properties.js, test/Integration/alternatives-test.js, test/unit/property-test.js
This PR uses a reference for an enum. There is already an issue open #375 and there has been a previous PR which has been closed due to inactivity.
New test cases have been added to cover the changes.
Thanks for reviewing it.
=> Use ref for enums (#375)

lib/paths.js
Add check if route.tags is undefined and use an empty array for filtering
=> fix: crash if grouping is set to `tags` but route is missing `options.tag`

index.d.ts, lib/definitions.js, optionsreference.md, test/Integration/alternatives-test.js, test/Integration/builder-test.js, test/Integration/definitions-test.js, test/Integration/responses-tests.js, usageguide.md
This is my reworked PR. @robmcguinness please check once you have time for it.
This PR changes the behavior for the `reuseDefinitions` option(make it more strict). Also, this fixes the [issue](https://github.com/hapi-swagger/hapi-swagger/issues/366).
These changes apply to how the plugin reuses definitions. For now to really reuse the definition model you need to keep the definition and labels the same.
=> Fix issue 366

lib/utilities.js, test/unit/utilities-test.js
This PR is addressed to update the function `Utilities.appendQueryString` behavior. As noted in this [issue](https://github.com/hapi-swagger/hapi-swagger/issues/786), this function does not cover duplication query keys after my last changes.
Until my previous changes, this function completely overrides all query string and append a new one. I am not sure that it was correct behavior because the function is called `appendQueryString` not `overrideQueryString` or `setQueryString`. My new implementation takes it into account more precisely. So, this function does not override the current query string, instead of function adds a new query to it if missed or updates the existing one.
=> Fix issue #786

lib/properties.js, test/unit/property-test.js
Check if a field is already added to the required list
=> fix: check before adding a required field to the list

index.d.ts, lib/builder.js, lib/defaults.js, lib/index.js, optionsreference.md, templates/index.html
There are quite a few Swagger UI settings which someone using hapi-swagger might want to change. Instead of adding them all as plugin options this PR adds a single `uiOptions` setting which can be an object of arbitrary options passed to Swagger UI.
=> Add uiOptions setting to pass arbitrary options to Swagger UI

index.d.ts, lib/index.js, optionsreference.md, public/extend.js, usageguide.md
This PR adds an `unsorted` value for both `options.sortTags` and `options.sortEndpoints` which disables explicit sorting of tags and endpoints by the swagger UI.
This change is needed to be able to define the order of the tag groups in the UI via `options.tags`. While the documentation claimed that was the default behavior, groups were actually always sorted alphabetically without any way to change their order.
=> Add 'unsorted' option for sortTags and sortEndpoints

lib/properties.js, test/Integration/alternatives-test.js, test/unit/property-test.js
The thing that led to this PR is the OpenAPI v3 AnyOf generation. In Redocly (which we use) at least this shows the type ('object', 'string', 'number') on the alternatives-selector by default.
To show a more descriptive label you can add the `title` property to each of the alternatives, which gets you something like this:
This PR adds support for the `title`-property to hapi-swagger through the `title` Joi.meta() property.
```typescript
joiModel.meta({ title: 'SIF' })
```
I've added it very generically, as this property can be added to any schema in both OpenAPI 2 & 3, and display after the property type in Redocly:
```typescript
status: Joi.string().meta({ title: 'QuotationStatus' }),
```
It was deceptively simple to add, so please let me know if I missed any edge-cases, added it to the …
=> Add title to property based on Joi meta property

lib/builder.js, package.json, test/Integration/dereference-test.js
Method "deRefrence" does not clear the schema for openapi version 3.
=> Fixed problem with "deReference" on openapi v3.

lib/builder.js, test/Integration/dereference-test.js
See https://github.com/hapi-swagger/hapi-swagger/pull/884#issuecomment-2164141354
=> Retain components.securitySchemes when deReference is enabled in OAS v3

lib/index.js, test/Integration/plugin-test.js
Fixes https://github.com/hapi-swagger/hapi-swagger/issues/1014
After adding query tags to url, attempting to remove the tags will always show the previous tags.
Best to reset the jsonPath when there are no query tags.
Added an integration test as well.
=> Reset jsonPath to defaults if no query tags
