hapi-swagger/hapi-swagger

lib/index.js
documentation path didn't used auth options.
=> auth for documentationpath

public/swaggerui/swagger.html
Small change, awaiting amendments.
=> Changed to the correct link for swagger.

package.json
```
mocha --reporter min
32 passing (333ms)
```
=> upgrade boom@2.7.x, hoek@2.12.x, joi@6.1.x

package.json
handlebars@1.3.0 includes the vulnerable package uglify-js@2.3.6.
Updating to latest handlebars@^4.0.0.
=> package.json: Update Handlebars (security update)

public/swaggerui/index.html
Changed the static title to use the handlebars title assigned by the user
=> Changed title to use user assigned title

lib/paths.js
A little fix to make operation ids unique.
The swagger validator cries about thoses duplicated operation ids.
=> mod - little fix to have unique operation ids,

CONTRIBUTING.md, README.md
https://github.com/blog/1184-contributing-guidelines
=> move plugin testing section to contributing.md

lib/properties.js, test/unit/property-test.js
fixes glennjones/hapi-swagger#322
=> Manage custom JOI extension

package.json
=> Update hapi.js to latest major version 16.0.1

optionsreference.md
=> haeders -> headers

examples/dot-grouping.js, examples/versions.js, lib/definitions.js, optionsreference.md, usageguide.md
Correcting some grammar stuff, and a file path
=> Minor grammar fixes

lib/builder.js, lib/index.js, test/Integration/plugin-test.js
Hi I d'like to add cors option to hapi-swagger plugin, please review.
Regards 
Dawid
=> added to hapi swagger route cors configuration as option

lib/builder.js, lib/defaults.js, lib/paths.js, test/Integration/grouping-test.js
This will allow us to group endpoints in the swagger UI based on the hapi controller tags
=> Added a grouping setting to choose between path and tags grouping

usageguide.md
change `joi.nunber` to `joi.number`
=> change `joi.nunber` to `joi.number`

lib/paths.js
only because grep didn't like it during debugging
=> fix 'vaildation' typoes

lib/properties.js
Fixes #454 
Reference to existing code:
https://github.com/glennjones/hapi-swagger/blob/c379231246955c7ceb8e6c7b46d15903e86bc32b/lib/properties.js#L518-L529
=> remove undefined item from Joi.try() alternatives structures

optionsreference.md
Thanks for making hapi swagger!
=> Fixing spelling issue

lib/builder.js, test/Integration/builder-test.js
Allow user to add x-* outside of info object
=> Allow user to add x-* outside of info object

lib/paths.js, lib/utilities.js, test/Integration/plugin-test.js, test/unit/utilities-test.js
Resolves #550 
I tried to follow the existing code philosophy as much as possible. I thus mutated some objects since it was already the case.
=> Allow vendor extensions at route level

lib/builder.js, test/Integration/proxy-test.js
Pull first (orginating) entry out of host and proto forwarding headers.
=> Add support for multihop proxy headers.

.gitignore, .travis.yml, .vscode/launch.json, package-lock.json, package.json, test/Integration/builder-test.js
Also run test against Hapi 17 and Hapi 18. Closes #557
=> feat: hapi 18 peer dependency support

package-lock.json, package.json
Fixes https://github.com/glennjones/hapi-swagger/issues/634
=> Upgrade to Joi v16.1.8

lib/index.js, lib/paths.js, test/Integration/path-test.js
=> Faster json generation

optionsreference.md
=> ✏️ fix typo

lib/parameters.js, lib/properties.js, test/Integration/lout-test.js, test/Integration/query-test.js, test/unit/property-test.js
=> Fix swagger validation errors

index.d.ts, lib/builder.js, lib/defaults.js, lib/index.js, optionsreference.md, templates/index.html, test/Integration/plugin-test.js
@robmcguinness something like this? Do you think I should add other missing display options or not bother?
=> Add support for tryItOutEnabled option

index.d.ts, optionsreference.md
@robmcguinness sorry I just realised that the TS type was wrong 🤦
=> Fix typescript type for tryItOutEnabled option

lib/properties.js, test/unit/property-test.js, usageguide.md
PR for this issue: https://github.com/glennjones/hapi-swagger/issues/735
=> FIX to support OpenApi 2.0 XML properties for schemas

lib/properties.js, test/unit/property-test.js, usageguide.md
I have prepared this pull request to address issue #740 that I opened some days ago.
I have added 2 new tests, and the second one tests the new functionality of this PR. 
The first one isn't directly related to the new functionality, but it is a case that it seems to me that it was missing. If you feel that is redundant, let me know to remove it.
Please have a look and send my any comments you may have
=> feat: add support for format field in integer properties

examples/assets/routes-simple.js, lib/builder.js, lib/definitions.js, lib/group.js, lib/hash.js, lib/index.js, lib/parameters.js, lib/paths.js, lib/properties.js, lib/responses.js, lib/sort.js, lib/utilities.js, lib/validate.js, test/helper.js
I have fixed a lot of jsDoc definitions according to [documentation](https://jsdoc.app/index.html). I can see that there are a ton of places where the definition is not correct, but I need more time to clearly define the right type of definition. I will create another PR to fix all of them.
=> fix: Fix jsDoc definitions

lib/properties.js, lib/utilities.js, test/Integration/builder-test.js, test/unit/utilities-test.js
This PR fixes [issue](https://github.com/hapi-swagger/hapi-swagger/issues/711).
=> Fix issue 711

lib/parameters.js, test/Integration/path-test.js
This PR fixes [this](https://github.com/hapi-swagger/hapi-swagger/issues/704).
=> fix: Fix issue #704

lib/paths.js, lib/properties.js, lib/responses.js, test/unit/utilities-test.js
Long story short, the original idea of this PR was to improve test coverage by adding test suites to uncovered lines and reach 99% of coverage. After some investigation, I realized that it is impossible till some refactoring, SO I did small and careful refactoring to improve the readability of the code base.
=> fix: Improve test coverage and small refactoring

index.d.ts, lib/builder.js, lib/defaults.js, lib/index.js, lib/paths.js, test/Integration/wildcard-routes.js
This PR adds a new option to the plugin and is addressed to resolve another [PR ](https://github.com/hapi-swagger/hapi-swagger/pull/739)in a bit more flexible way.
=> feat: resolve PR #739

lib/properties.js, test/Integration/file-test.js
=> fix(oas3): generate correct schema for uploaded file in a requestBody

lib/properties.js, test/Integration/array-test.js, test/unit/property-test.js
=> feat: use anyOf if multiple items type in array
